import type { Metadata } from "next";
import { GeistMono } from 'geist/font/mono';
import "./globals.css";
import AppShell from "@/app/components/AppShell";

export const metadata: Metadata = {
  title: "Chloe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistMono.variable}`}>
        <AppShell>{children}</AppShell>
      </body>
    </html>
  )
}
